### PR TITLE
logdir variable made available to ensure logs are centrally located

### PR DESCRIPTION
**Pull request by kenhughesiam**
This code addition enables all crowd log files to placed under the same directory. The
logdir var is set and used, additional template files have been included for relevant logging handlers.  A 5 day retention period has also been set within templates, other than that the log handler templates are standard. Catalina.out also stored within $logdir.

### CODE REVIEW

**Comment by wesmiles** [comment]
Hi, I also need the ability to set the log directory of my atlassian apps including crowd.  

Could this PR be merged please?

**Comment by joshbeard** [comment]
I appreciate the pull request and apologize for the delay in responding to this. I agree that improvements to logging should be incorporated here, though I'm not sure about managing the entirety of `server.xml` as-is. I've used Augeas to manage attributes on the connector in `server.xml` that the installation provides. How would you feel about doing the same for the log customizations? I'm happy to do it. I'm also contemplating making the module's management of the 3 log property files optional.

**Comment by joshbeard** [comment]
I have the changes in a branch called "pr23_rework": https://github.com/joshbeard/puppet-crowd/compare/master...joshbeard:pr23_rework?expand=1

If you'd like to rebase your branch against master, I can do a PR of my changes into your branch so that your contribution is preserved (unless you know another way). Otherwise, you can review mine and I'll merge to master.

**Comment by joshbeard** [comment]
Disregard, I'll clean up the commits on my branch to preserve authorship.

**Comment by joshbeard** [comment]
I updated my branch to rebase including yours: https://github.com/joshbeard/puppet-crowd/compare/master...joshbeard:pr23_rework?expand=1

**Comment by joshbeard** [comment]
This has been merged to master: https://github.com/joshbeard/puppet-crowd/commit/b5670074affd70a0415ac7ef12fc6e4b5b385346
https://github.com/joshbeard/puppet-crowd/commit/494ec6833fbb7976429776c45885d44880af406e

**Pull request closed without merging**
